nn = input("Digite algo: ")
print('O tipo primitivo desse valor é: ', type(nn))
print('Este valor pode ser .. ')
print('Só tem espaço? ',nn.isspace())
print('É um número? ',nn.isnumeric())
print('É alfabético? ',nn.isalpha())
print('É alfanumérico? ', nn.isalnum())
print('Está em maiúsculas? ', nn.isupper())
print('Está em minúsculas? ', nn.islower())
print('Está capitalizada? ', nn.istitle())